### ISSUE TITLE
Better SQL Server Error messages?

### ISSUE THREAD

**Issue by drewsonian** [realestateconz/MssqlBundle#13]
I've been using this and it's works well, except for one thing, which I suspect is probably a FreeTDS thing.  When I get an error message back, I typically get something cryptic like 

```
An exception occurred while executing 'SQL Statement Here' with params [2]:\ \ SQLSTATE[HY000]: 
General error: 207 General SQL Server error: Check messages from the SQL Server [207] (severity 16) [(null)]
```

My issue is that "General error: 207" line - if I copy and paste the SQL statement into SQL Server Mgmt Studio, I can get an error message that is more useful like:

```
Msg 207, Level 16, State 1, Line 1
Invalid column name 'modified_by_user'.
```

Is there a way to get this more detailed error message back?  Should I be asking the FreeTDS contributors instead?

**Comment by oliver-realestate** [comment]
Hi,

my assumption is that the driver doesn't return a more detailed error message, hence nothing more can get displayed.

This Bundle isn't under active development, we're still using it but there are no plans to extend it, at this stage.
However if you find a solution to this and are willing to create a pull request I'd be happy to merge it.

**Comment by drewsonian** [comment]
Thanks for your response, from the other research that I've done, it does look like the driver doesn't return anything more detailed.  I know it's not under active development, but I am planning on using it during an interim time while we migrate from SQL Server to Postgres or MySQL and very much appreciate the work that you've put into it.

If I come across anything about more detailed error messages or anything else that could enhance it, I'll definitely submit a PR.
